### ISSUE TITLE
Support for docker on macOS?

### ISSUE THREAD

**Issue by MarcoLeongDev** [jams246/mira#4]
I have tested this image with macOS, looks like it is unable to capture the information for for macOS. For example:
- the OS info shows `Linux version 5.10.76-linuxkit`. This seems like a layer between macOS and docker container
- the total memory is the amount of memory allocated to docker instead of the OS's

Question:
I am using the default compose example when testing
- Is there a way to configure mira to display the macOS information?

compose.yml
```
version: "3.8"
services:
  mira:
    image: jams246/mira
    container_name: mira
    pid: host
    ports:
      - "44356:44356"
      - "44357:44357"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
```

many thanks
